export enum BackendActionTypes {
  GetRequestList = "GET_REQUEST_LIST",
  LoginUser = "LOGIN_USER_REQUESTED",
  GetRequirementDetails = "GET_REQUIREMENT_DETAILS",
  CreateUserProfile = "CREATE_USER_PROFILE",
  DeleteUserProfile = "DELETE_USER_PROFILE",
  GetUserDetails = "GET_USER_DETAILS",
  UpdateUserProfile = "UPDATE_USER_PROFILE",
  GetSuggestions = "GET_SUGGESTIONS",
  GetEmployeesList = "GET_EMPLOYEES_LIST",
  GetEmployeeDetails = "GET_EMPLOYEE_DETAILS",
  CreateEmployee = "CREATE_EMPLOYEE",
  UpdateEmployee = "UPDATE_EMPLOYEE",
  DeleteEmployee = "DELETE_EMPLOYEE",
}
